### PR TITLE
fix(slider): focus draghandle when component is clicked, closes #15

### LINKED ISSUE #15: Keyboard navigation does not work when slider is focused by clicking on the track
Also do we need to prevent the bubbling of the events. Currently, for example, hitting the home/end keys will bubble up to the parent elements.

### PR DESCRIPTION
**Pull request by KirilNN**

### CODE REVIEW

**Comment by underlog** [comment]
There are two outstanding problems with the current keyboard behavior. Not sure if they should be handled in this pull request, but it somewhat feels right to me.

1. The slider has no visual clue that it is currently focused. It seems like it is part of the document tab order. 

2. When in vertical mode, the up/down arrows scroll the document.

Both of these are reproducible in the documentation index article.

**Comment by KirilNN** [comment]
Problem #1 will be addressed in https://github.com/telerik/kendo-react-inputs/issues/28

File: src/slider/Slider.jsx [hunk 1]
```diff
@@ -135,16 +135,23 @@ class Slider extends React.Component {
...
+        if (handler && !disabled) {
             let value = handler(this.props);
             value = util.trimValue(max, min, value);
             this.props.onChange({ value });
         }
     };
 
+    onComponentClick = () => {
+        if (!this.props.disabled) {
+            ReactDOM.findDOMNode(this).getElementsByClassName('k-draghandle')[0].focus();
```
Comment (rusev) [inline src/slider/Slider.jsx]: You could use `this.componentElements().dragHandle` to get reference to the drag handle.
